// <auto-generated />
using System;
using AssetsMangment.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AssetsMangment.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260623042008_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AssetsMangment.Models.Asset", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("FirstSeen")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("LastSeen")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Metadata")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<int>("Source")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("Tags")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("Id");

                    b.HasIndex("Type", "Value")
                        .IsUnique();

                    b.ToTable("Assets");
                });

            modelBuilder.Entity("AssetsMangment.Models.AssetRelationship", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("SourceAssetId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TargetAssetId")
                        .HasColumnType("uuid");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("SourceAssetId");

                    b.HasIndex("TargetAssetId");

                    b.ToTable("AssetRelationships");
                });

            modelBuilder.Entity("AssetsMangment.Models.AssetRelationship", b =>
                {
                    b.HasOne("AssetsMangment.Models.Asset", "SourceAsset")
                        .WithMany("OutgoingRelationships")
                        .HasForeignKey("SourceAssetId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AssetsMangment.Models.Asset", "TargetAsset")
                        .WithMany("IncomingRelationships")
                        .HasForeignKey("TargetAssetId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("SourceAsset");

                    b.Navigation("TargetAsset");
                });

            modelBuilder.Entity("AssetsMangment.Models.Asset", b =>
                {
                    b.Navigation("IncomingRelationships");

                    b.Navigation("OutgoingRelationships");
                });
#pragma warning restore 612, 618
        }
    }
}
